---
settings:
  parallel: true

driver:
  name: dokken
  chef_version: latest
  use_sudo: false
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: centos-7
  driver:
    image: dokken/centos-7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y update

- name: amazonlinux-2
  driver:
    image: dokken/amazonlinux-2
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y update

- name: fedora-27
  driver:
    image: dokken/fedora-27
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y update

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

# kitchen-docken does not work for ubuntu-18.04 because changes in systemd
# https://github.com/moby/moby/issues/38749
# testing with real VM in the cloud does not show this error
# - name: ubuntu-18.04
#   driver:
#     image: dokken/ubuntu-18.04
#     pid_one_command: /bin/systemd
#     intermediate_instructions:
#       - RUN /usr/bin/apt-get update

verifier:
  name: inspec

suites:
- name: default
  run_list:
    - recipe[opendkim-milter]
  verifier:
    inspec_tests:
    - test/integration/default
  attributes:

