---
settings:
  parallel: true

driver:
  name: dokken
  chef_version: latest
  use_sudo: false
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: centos-7
  driver:
    image: dokken/centos-7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y update

- name: amazonlinux-2
  driver:
    image: dokken/amazonlinux-2
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y update

- name: fedora-27
  driver:
    image: dokken/fedora-27
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y update

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

# kitchen-docken does not work for ubuntu-18.04 because changes in systemd
# https://github.com/moby/moby/issues/38749
# testing with real VM in the cloud does not show this error
# - name: ubuntu-18.04
#   driver:
#     image: dokken/ubuntu-18.04
#     pid_one_command: /bin/systemd
#     intermediate_instructions:
#       - RUN /usr/bin/apt-get update

verifier:
  name: inspec

suites:
- name: default
  data_bags_path: "test/integration/data_bags"
  run_list:
    - recipe[opendkim-milter]
  verifier:
    inspec_tests:
    - test/integration/default
  attributes:
    opendkim-milter:
      services:
        verifier:
          base_path:       '/opt/dkim'
          config:
            PidFile:       '/var/run/opendkim/verifier.pid'
            Mode:          'v'
            Syslog:        'yes'
            SyslogSuccess: 'yes'
            LogWhy:        'yes'
            UserID:        'opendkim:bin'
            Socket:        'local:/var/run/opendkim/verifier.sock'
            Umask:         '007'
            OversignHeaders: 'From'
          group: 'bin'
          user_targets:
            - 'mysql.target'
        signer:
          base_path:          '/opt/dkim'
          config:
            PidFile:          '/var/run/opendkim/signer.pid'
            Mode:             's'
            Syslog:           'yes'
            SyslogSuccess:    'yes'
            LogWhy:           'yes'
            UserID:           'opendkim:bin'
            Socket:           'local:/var/run/opendkim/signer.sock'
            Umask:            '007'
            OversignHeaders:  'From'
            Canonicalization: 'relaxed/simple'
            InternalHosts:    'refile:/opt/dkim/TrustedHosts'
            KeyTable:         'refile:/opt/dkim/KeyTable'
            SigningTable:     'refile:/opt/dkim/SigningTable'
            SignatureAlgorithm: 'rsa-sha256'
          group: 'bin'
          config_files:
            TrustedHosts:
            - '127.0.0.1'
            - '::1'
            KeyTable:
              default._domainkey.example.com: 'example.com:default:/etc/opendkim/keys/example.private'
              default._domainkey.test.com: 'test.com:default:/etc/opendkim/keys/test.private'
            SigningTable:
              '*@example.com': 'default._domainkey.example.com'
              '*@test.com': 'default._domainkey.test.com'
          databag_defaults:
            databag: 'dkimkeys'
            item: 'example'
            field: 'key'
          databag_files:
            keys/example.private:
              field: 'content'
              mode: '0600'
            keys/test.private:
              item: 'test'
